name: 'Execução Integrada'

on:
  workflow_dispatch:

jobs:
  inspection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn install
      - name: Padronização de código (Lint)
        run: yarn lint

  unit:
    runs-on: ubuntu-latest
    needs: [inspection]
    steps:
      - uses: actions/checkout@v4
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn install
      - name: Testes de Unidade
        run: yarn run test

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [unit]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Instalando dependências
        run: npm install
      - name: Executando testes E2E com Cypress
        run: npm run test:e2e
        env:
          CYPRESS_BASE_URL: 'https://automationexercise.com'

      # Upload de relatórios e screenshots
      - name: Upload de relatório de testes
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-de-testes
          path: cypress/reports

      - name: Upload de screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: cypress/screenshots

  deploy:
    runs-on: ubuntu-latest
    needs: [e2e-tests]
    steps:
      - name: Deploy
        run: echo "Deploy step"
