# CI de Nível 01 - Disparo manual a partir de 1 clique

name: 'Execução Manual'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Instalando dependências
        run: npm install

      - name: Executando testes E2E com Cypress
        run: npm run test

      # Upload de relatório de testes e screenshots como artefato
      - name: Upload de relatório de testes
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-de-testes
          path: cypress/reports

      - name: Upload de screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: cypress/screenshots
