# CI de Nível 01 - Disparo manual a partir de 1 clique

# nome que vai aparecer la nas opções de pipe
name: 'Execução Manual'

# regras de disparo de execução (triggers/gatilhos)
# gatilho de exec manual = workflow_dispatch

on:
   workflow_dispatch:

jobs: 

  # descrição do job
  e2e-tests:

    # maquina que job vai executar
    runs-on: ubuntu-latest

    # passo a passo das açoes do job
    steps:

      - uses: actions/checkout@v4

     # - uses: actions/setup-node@v4
     #   with:
     #     node-version: lts/*

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      #- name: Instalando Playwright
      #  run: yarn playwright install   

      - name: Teste E2E (end-to-end)
        run: yarn run e2e

      # disponibilizando relatorio (artefato)  
      # passed, failed, cancelled
      #- uses: actions/upload-artifact@v4
      #  if: ${{ !cancelled() }}
      #  with:
      #    name: relatorio-de-testes
      #    path: ./playwright-report
