name: 'Execução Integrada'

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  inspection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn install
      - name: Padronização de código (Lint)
        run: yarn lint

  unit:
    runs-on: ubuntu-latest
    needs: [inspection]
    steps:
      - uses: actions/checkout@v4
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn install
      - name: Testes de Unidade
        run: yarn run test

  e2e-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, windows-2022, macos-14]
    runs-on: ${{ matrix.os }}
    needs: [unit]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Instalando dependências
        run: npm install

      - name: Cypress Info
        run: npx cypress info

      - name: Executando testes E2E com Cypress
        run: npm run e2e
        env:
          CYPRESS_BASE_URL: 'https://automationexercise.com'

      # Geração do Relatório Mochawesome
      - name: Gerar relatório com mochawesome
        if: ${{ always() }}
        run: npx mochawesome-merge cypress/reports/*.json > mochawesome.json && npx marge mochawesome.json

      # Upload do relatório de testes
      - name: Upload de relatório de testes
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-de-testes
          path: mochawesome-report

      # Upload de screenshots em caso de falha
      - name: Upload de screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: cypress/screenshots

  deploy:
    runs-on: ubuntu-latest
    needs: [e2e-tests]
    steps:
      - name: Deploy
        run: echo "Deploy step"
