# CI de Nível 01 - Disparo manual a partir de 1 clique

# Nome do pipeline
name: 'Execução Manual'

# Gatilho para execução manual
on:
  workflow_dispatch:

jobs:
  # Job de testes E2E com Cypress
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Define o tempo limite de 30 minutos

    steps:
      # Baixa o código do repositório
      - uses: actions/checkout@v4

      # Configura o Node.js na versão LTS
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # Habilita o Corepack e configura o Yarn
      - name: Configurando Corepack para Yarn
        run: corepack enable && corepack prepare yarn@stable --activate

      # Instala dependências, incluindo Cypress (sem --immutable)
      - name: Instalando dependências
        run: yarn install

      # Cria o diretório cypress/reports, caso não exista
      - name: Criando diretório de relatórios
        run: mkdir -p cypress/reports

      # Executa testes E2E com Cypress
      - name: Executando testes E2E com Cypress
        run: yarn run e2e
        env:
          CYPRESS_BASE_URL: 'https://automationexercise.com'

      # Gera o relatório consolidado do mochawesome (se houver arquivos JSON)
      - name: Gerando relatório mochawesome consolidado
        if: ${{ always() }}
        run: |
          if ls cypress/reports/*.json 1> /dev/null 2>&1; then
            npx mochawesome-merge cypress/reports/*.json > mochawesome.json && npx marge mochawesome.json
          else
            echo "Nenhum relatório JSON encontrado para mesclar com mochawesome-merge."
          fi

      # Upload do relatório Mochawesome como artefato
      - name: Gerar e fazer upload do relatório de testes
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-de-testes
          path: cypress/reports

      # Verifica se o relatório BrowserStack existe
      - name: Verificar existência do relatório BrowserStack
        run: |
          if [ -f "browserstack-cypress-report.json" ]; then
            echo "BrowserStack report found"
          else
            echo "No BrowserStack report found"
          fi

      # Upload do relatório BrowserStack como artefato, se existir
      - name: Upload do relatório BrowserStack
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: browserstack-cypress-report
          path: browserstack-cypress-report.json
          if-no-files-found: ignore

      # Upload de screenshots em caso de falha
      - name: Upload de screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: cypress/screenshots
