# CI de Nível 01 - Disparo manual a partir de 1 clique
name: 'Execução Manual'

# Gatilho para execução manual
on:
  workflow_dispatch:

jobs:
  # Job de inspeção de código
  inspection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn install

      - name: Padronização de código (Lint)
        run: yarn lint

  # Job de testes unitários
  unit:
    runs-on: ubuntu-latest
    needs: [inspection]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Instalando dependências
        run: yarn install

      - name: Executando testes unitários
        run: yarn run test

  # Job de testes E2E com Cypress
  e2e-tests:
    runs-on: ubuntu-latest
    needs: [unit]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Instalando dependências
        run: yarn install

      # Executa os testes E2E com Cypress
      - name: Executando testes E2E com Cypress
        run: yarn run e2e
        env:
          CYPRESS_BASE_URL: 'https://automationexercise.com'

      # Geração do Relatório Mochawesome
      - name: Gerar relatório com mochawesome
        if: ${{ always() }}
        run: npx mochawesome-merge cypress/reports/*.json > mochawesome.json && npx marge mochawesome.json

      # Upload do relatório de testes
      - name: Upload de relatório de testes
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-de-testes
          path: mochawesome-report

      # Upload de screenshots em caso de falha
      - name: Upload de screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: cypress/screenshots

  # Job de deploy
  deploy:
    runs-on: ubuntu-latest
    needs: [e2e-tests]
    steps:
      - name: Deploy
        run: echo "Step de deploy concluído com sucesso"
