# CI de Nível 03 – Disparo automático
name: 'Execução por Deploy'

# Configuração de disparo automático
on:
  workflow_run:
    workflows: ['Execução Manual'] # Nome do pipeline
    types:
      - completed

jobs:
  # Job de testes E2E com Cypress
  e2e-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # Baixa o código do repositório
      - uses: actions/checkout@v4

      # Configura o Node.js na versão LTS
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # Instala Yarn globalmente
      - name: Instalando Yarn
        run: npm install -g yarn

      # Instala dependências, incluindo o Cypress
      - name: Instalando dependências
        run: yarn install

      # Executa testes E2E com Cypress
      - name: Executando testes E2E com Cypress
        run: yarn run e2e
        env:
          CYPRESS_BASE_URL: 'https://automationexercise.com'

      # Geração do Relatório Mochawesome
      - name: Gerar relatório com mochawesome
        if: ${{ always() }}
        run: npx mochawesome-merge cypress/reports/*.json > mochawesome.json && npx marge mochawesome.json

      # Upload do relatório de testes como artefato
      - name: Upload de relatório de testes
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-de-testes
          path: mochawesome-report

      # Upload de screenshots em caso de falha
      - name: Upload de screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: cypress/screenshots
